spring:
  application:
    name: fastticket-user-service
  jackson:
    default-property-inclusion: NON_NULL
  datasource:
    url: ${DB_HOST:jdbc:postgresql://localhost:5432/users_db}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  mail:
    host: ${EMAIL_HOST:smtp.gmail.com}
    port: ${EMAIL_PORT:587}
    username: ${EMAIL_USERNAME:XXXXXXX}
    password: ${EMAIL_PASS:XXXXX}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: when-authorized

